### ISSUE TITLE
Extension Documentation

### ISSUE THREAD

**Issue by Swisskill** [TcM1911/stix2#52]
The instructions for creating new extensions, especially in regards to 
```stix2.NewExtensionDefinition```
and its field 
```extTypes []stix2.ExtensionType```
is rather vague. An example of how one might call this function would be helpful

**Comment by TcM1911** [comment]
I'd recommend reading section 7.3 in the specification. It documents this type and all of its fields.

**Comment by Swisskill** [comment]
It was more of a syntactical issue using the package, but I realized part of the problem was my using the wrong function. I was attempting to use  "NewExtensionDefinition()" where "OptionExtension" belonged
