### ISSUE TITLE
Potential Extension Error

### ISSUE THREAD

**Issue by wrbrant** [TcM1911/stix2#60]
extension_types does not write out to a file correctly. Instead, it returns a base64 encoded string that, from what I can tell, does not map to its original string. As another example, ["property-extension"] becomes "BA==". This issue is only in "extension_types" in the extension-definition, not in "extension-type" found in standard STIX object.

Here is the code. The assignment of "e" to NewExtensionDefinition is copied directly from the [extension_test.go](https://github.com/TcM1911/stix2/blob/master/extension_test.go), lines 81-88:
![Screenshot from 2023-07-15 14-29-55](https://github.com/TcM1911/stix2/assets/70920033/23604f5e-b438-4a4d-82a8-94d34ed5c4e2)

Here is the terminal output:
![Screenshot from 2023-07-15 14-30-46](https://github.com/TcM1911/stix2/assets/70920033/0da62ff1-3175-4eaf-97c0-bab2fd5b1cd5)

Here is the file output:
![Screenshot from 2023-07-15 14-31-30](https://github.com/TcM1911/stix2/assets/70920033/18736206-1610-4916-ad0f-208cef1f50ae)

**Comment by wrbrant** [comment]
It does fix it. I have cloned the repository, created a branch, and added the fix. Can I push it to origin and make a merge request?

**Comment by TcM1911** [comment]
Yes go ahead and create a PR. Please include a test as part of the fix. Thanks.

**Comment by TcM1911** [comment]
Pull the latest [release](https://github.com/TcM1911/stix2/releases/tag/v0.10.3) for the fix.
